---
name: Please do not open issues in this repo
description: Choose one of the other repos below
title: Please do not open issues in this repo
body:
  - type: markdown
    attributes:
      value: |
        Please do not open issues in this repo
---
